// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC721Pausable$Type } from "./ERC721Pausable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC721Pausable"]: ERC721Pausable$Type;
    ["@openzeppelin/contracts/token/ERC721/extensions/ERC721Pausable.sol:ERC721Pausable"]: ERC721Pausable$Type;
  }

  interface ContractTypesMap {
    ["ERC721Pausable"]: GetContractReturnType<ERC721Pausable$Type["abi"]>;
    ["@openzeppelin/contracts/token/ERC721/extensions/ERC721Pausable.sol:ERC721Pausable"]: GetContractReturnType<ERC721Pausable$Type["abi"]>;
  }
}
