/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFractional__factory } from "./IFractional__factory";
export { Payment__factory } from "./Payment__factory";
