// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IFractional$Type } from "./IFractional";
import { Payment$Type } from "./Payment";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IFractional"]: IFractional$Type;
    ["Payment"]: Payment$Type;
    ["contracts/Payment.sol:IFractional"]: IFractional$Type;
    ["contracts/Payment.sol:Payment"]: Payment$Type;
  }

  interface ContractTypesMap {
    ["IFractional"]: GetContractReturnType<IFractional$Type["abi"]>;
    ["Payment"]: GetContractReturnType<Payment$Type["abi"]>;
    ["contracts/Payment.sol:IFractional"]: GetContractReturnType<IFractional$Type["abi"]>;
    ["contracts/Payment.sol:Payment"]: GetContractReturnType<Payment$Type["abi"]>;
  }
}
