// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IFractional$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IFractional",
  "sourceName": "contracts/Payment.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "homeId",
          "type": "uint256"
        }
      ],
      "name": "homeUnit",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "totalQty",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "unitCost",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "sold",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IFractional",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFractional$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/Payment.sol:IFractional",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFractional$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IFractional",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFractional$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/Payment.sol:IFractional",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFractional$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IFractional",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFractional$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/Payment.sol:IFractional",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFractional$Type["abi"]>>;
}
