// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Home$Type } from "./Home";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Home"]: Home$Type;
    ["contracts/Home.sol:Home"]: Home$Type;
  }

  interface ContractTypesMap {
    ["Home"]: GetContractReturnType<Home$Type["abi"]>;
    ["contracts/Home.sol:Home"]: GetContractReturnType<Home$Type["abi"]>;
  }
}
