// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC1155Burnable$Type } from "./ERC1155Burnable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC1155Burnable"]: ERC1155Burnable$Type;
    ["@openzeppelin/contracts/token/ERC1155/extensions/ERC1155Burnable.sol:ERC1155Burnable"]: ERC1155Burnable$Type;
  }

  interface ContractTypesMap {
    ["ERC1155Burnable"]: GetContractReturnType<ERC1155Burnable$Type["abi"]>;
    ["@openzeppelin/contracts/token/ERC1155/extensions/ERC1155Burnable.sol:ERC1155Burnable"]: GetContractReturnType<ERC1155Burnable$Type["abi"]>;
  }
}
