// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC721Enumerable$Type } from "./ERC721Enumerable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC721Enumerable"]: ERC721Enumerable$Type;
    ["@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol:ERC721Enumerable"]: ERC721Enumerable$Type;
  }

  interface ContractTypesMap {
    ["ERC721Enumerable"]: GetContractReturnType<ERC721Enumerable$Type["abi"]>;
    ["@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol:ERC721Enumerable"]: GetContractReturnType<ERC721Enumerable$Type["abi"]>;
  }
}
