// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { FractionalizeNFT$Type } from "./FractionalizeNFT";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["FractionalizeNFT"]: FractionalizeNFT$Type;
    ["contracts/FractHome.sol:FractionalizeNFT"]: FractionalizeNFT$Type;
  }

  interface ContractTypesMap {
    ["FractionalizeNFT"]: GetContractReturnType<FractionalizeNFT$Type["abi"]>;
    ["contracts/FractHome.sol:FractionalizeNFT"]: GetContractReturnType<FractionalizeNFT$Type["abi"]>;
  }
}
